object Modules {
    const val app = ":app"
    const val coreUi = ":core-ui"
    const val data = ":data"
    const val domain = ":domain"
    const val coreApi = ":core-api"
    const val commonResources = ":common-resources"
    const val presentation = ":presentation"
    const val commonModels = ":common-models"
    const val uiLibrary = ":ui-library"
    const val commonData = ":common-data"
    const val coreCatalogs = ":core-catalogs"
    const val uiBookDetails = ":ui-book-details"
    const val uiExplore = ":ui-explore"
    const val uiHistory = ":ui-history"
    const val uiReader = ":ui-reader"
    const val uiSettings = ":ui-settings"
    const val uiSources = ":ui-sources"
    const val uiTTS = ":ui-tts"
    const val uiUpdates = ":ui-updates"
    const val uiChapterDetails = ":ui-chapter-detail"
    const val uiWeb = ":ui-web"
    const val uiAbout = ":ui-about"
    const val uiAppearance = ":ui-appearance"
    const val uiDownloader = ":ui-downloader"
    const val uiComponents = ":ui-components"
    const val uiImageLoader = ":ui-image-loader"
    const val commonExtensions = ":common-extensions"

}