package ireader.presentation.ui.core.theme.themes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// ============================================================================
// Webnovel-inspired vibrant themes — bold, saturated, xianxia/webcomic palettes.
// ============================================================================

// ---- Royal Purple (Webnovel signature) -------------------------------------
val WebnovelRoyalLightThemeColors = lightColorScheme(
    primary = Color(0xFF7B2FF7),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFEADDFF),
    onPrimaryContainer = Color(0xFF250056),
    secondary = Color(0xFF625B71),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE8DEF8),
    onSecondaryContainer = Color(0xFF1D192B),
    tertiary = Color(0xFFFFB300),
    onTertiary = Color(0xFF3E2E00),
    tertiaryContainer = Color(0xFFFFE08A),
    onTertiaryContainer = Color(0xFF261900),
    error = Color(0xFFBA1A1A),
    errorContainer = Color(0xFFFFDAD6),
    onError = Color(0xFFFFFFFF),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFFBFF),
    onBackground = Color(0xFF1C1B1F),
    surface = Color(0xFFFFFBFF),
    onSurface = Color(0xFF1C1B1F),
    surfaceVariant = Color(0xFFEDE3F4),
    onSurfaceVariant = Color(0xFF49454F),
    outline = Color(0xFF7A757F),
    inverseOnSurface = Color(0xFFF4EFF4),
    inverseSurface = Color(0xFF313033),
    inversePrimary = Color(0xFFD3BBFF),
)

val WebnovelRoyalDarkThemeColors = darkColorScheme(
    primary = Color(0xFFCBA6FF),
    onPrimary = Color(0xFF3B0086),
    primaryContainer = Color(0xFF551BB3),
    onPrimaryContainer = Color(0xFFEADDFF),
    secondary = Color(0xFFCBC2DB),
    onSecondary = Color(0xFF332D41),
    secondaryContainer = Color(0xFF4A4458),
    onSecondaryContainer = Color(0xFFE8DEF8),
    tertiary = Color(0xFFFFCB42),
    onTertiary = Color(0xFF3E2E00),
    tertiaryContainer = Color(0xFF5A4300),
    onTertiaryContainer = Color(0xFFFFE08A),
    error = Color(0xFFFFB4AB),
    errorContainer = Color(0xFF93000A),
    onError = Color(0xFF690005),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF14121A),
    onBackground = Color(0xFFE7E0EB),
    surface = Color(0xFF14121A),
    onSurface = Color(0xFFE7E0EB),
    surfaceVariant = Color(0xFF2A2533),
    onSurfaceVariant = Color(0xFFCAC2D6),
    outline = Color(0xFF948FA0),
    inverseOnSurface = Color(0xFF14121A),
    inverseSurface = Color(0xFFE7E0EB),
    inversePrimary = Color(0xFF7B2FF7),
)

// ---- Crimson Phoenix --------------------------------------------------------
val CrimsonPhoenixLightThemeColors = lightColorScheme(
    primary = Color(0xFFD32F2F),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDAD6),
    onPrimaryContainer = Color(0xFF410002),
    secondary = Color(0xFFFF7043),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDBCF),
    onSecondaryContainer = Color(0xFF370E00),
    tertiary = Color(0xFFFFC107),
    onTertiary = Color(0xFF3E2E00),
    tertiaryContainer = Color(0xFFFFE08A),
    onTertiaryContainer = Color(0xFF261900),
    error = Color(0xFFBA1A1A),
    errorContainer = Color(0xFFFFDAD6),
    onError = Color(0xFFFFFFFF),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFFBFF),
    onBackground = Color(0xFF201A19),
    surface = Color(0xFFFFFBFF),
    onSurface = Color(0xFF201A19),
    surfaceVariant = Color(0xFFFFE5DF),
    onSurfaceVariant = Color(0xFF534340),
    outline = Color(0xFF85736F),
    inverseOnSurface = Color(0xFFFBEEEC),
    inverseSurface = Color(0xFF362F2E),
    inversePrimary = Color(0xFFFFB4AB),
)

val CrimsonPhoenixDarkThemeColors = darkColorScheme(
    primary = Color(0xFFFF8A80),
    onPrimary = Color(0xFF690005),
    primaryContainer = Color(0xFF93000A),
    onPrimaryContainer = Color(0xFFFFDAD6),
    secondary = Color(0xFFFFB59D),
    onSecondary = Color(0xFF5A1B00),
    secondaryContainer = Color(0xFF7C2D0E),
    onSecondaryContainer = Color(0xFFFFDBCF),
    tertiary = Color(0xFFFFD54F),
    onTertiary = Color(0xFF3E2E00),
    tertiaryContainer = Color(0xFF5A4300),
    onTertiaryContainer = Color(0xFFFFE08A),
    error = Color(0xFFFFB4AB),
    errorContainer = Color(0xFF93000A),
    onError = Color(0xFF690005),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF1A1110),
    onBackground = Color(0xFFF1DEDA),
    surface = Color(0xFF1A1110),
    onSurface = Color(0xFFF1DEDA),
    surfaceVariant = Color(0xFF36211D),
    onSurfaceVariant = Color(0xFFE7BDB5),
    outline = Color(0xFFA08C88),
    inverseOnSurface = Color(0xFF1A1110),
    inverseSurface = Color(0xFFF1DEDA),
    inversePrimary = Color(0xFFD32F2F),
)

// ---- Azure Cultivator -------------------------------------------------------
val AzureCultivatorLightThemeColors = lightColorScheme(
    primary = Color(0xFF0091EA),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFCBE6FF),
    onPrimaryContainer = Color(0xFF001D33),
    secondary = Color(0xFF00BCD4),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFB3F0FA),
    onSecondaryContainer = Color(0xFF00363F),
    tertiary = Color(0xFF7C4DFF),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFE7DEFF),
    onTertiaryContainer = Color(0xFF21005D),
    error = Color(0xFFBA1A1A),
    errorContainer = Color(0xFFFFDAD6),
    onError = Color(0xFFFFFFFF),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFBFCFF),
    onBackground = Color(0xFF1A1C1E),
    surface = Color(0xFFFBFCFF),
    onSurface = Color(0xFF1A1C1E),
    surfaceVariant = Color(0xFFDCE8F4),
    onSurfaceVariant = Color(0xFF42474E),
    outline = Color(0xFF72777F),
    inverseOnSurface = Color(0xFFF0F0F3),
    inverseSurface = Color(0xFF2E3133),
    inversePrimary = Color(0xFF8FCDFF),
)

val AzureCultivatorDarkThemeColors = darkColorScheme(
    primary = Color(0xFF7FCFFF),
    onPrimary = Color(0xFF003353),
    primaryContainer = Color(0xFF004A75),
    onPrimaryContainer = Color(0xFFCBE6FF),
    secondary = Color(0xFF52DBF0),
    onSecondary = Color(0xFF00363F),
    secondaryContainer = Color(0xFF004F5A),
    onSecondaryContainer = Color(0xFFB3F0FA),
    tertiary = Color(0xFFCBBEFF),
    onTertiary = Color(0xFF35089A),
    tertiaryContainer = Color(0xFF5B30D4),
    onTertiaryContainer = Color(0xFFE7DEFF),
    error = Color(0xFFFFB4AB),
    errorContainer = Color(0xFF93000A),
    onError = Color(0xFF690005),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF0E141A),
    onBackground = Color(0xFFE1E2E6),
    surface = Color(0xFF0E141A),
    onSurface = Color(0xFFE1E2E6),
    surfaceVariant = Color(0xFF1E2A36),
    onSurfaceVariant = Color(0xFFC0C7D0),
    outline = Color(0xFF8A919A),
    inverseOnSurface = Color(0xFF0E141A),
    inverseSurface = Color(0xFFE1E2E6),
    inversePrimary = Color(0xFF0091EA),
)

// ---- Golden Empire ----------------------------------------------------------
val GoldenEmpireLightThemeColors = lightColorScheme(
    primary = Color(0xFFC8941E),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFE08A),
    onPrimaryContainer = Color(0xFF261900),
    secondary = Color(0xFF6D5E00),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFCE186),
    onSecondaryContainer = Color(0xFF211B00),
    tertiary = Color(0xFFB5460F),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDBCF),
    onTertiaryContainer = Color(0xFF3B0A00),
    error = Color(0xFFBA1A1A),
    errorContainer = Color(0xFFFFDAD6),
    onError = Color(0xFFFFFFFF),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFFBF2),
    onBackground = Color(0xFF1E1B13),
    surface = Color(0xFFFFFBF2),
    onSurface = Color(0xFF1E1B13),
    surfaceVariant = Color(0xFFF1E5C6),
    onSurfaceVariant = Color(0xFF4D4639),
    outline = Color(0xFF7F7667),
    inverseOnSurface = Color(0xFFF8F0E2),
    inverseSurface = Color(0xFF333027),
    inversePrimary = Color(0xFFF4C04C),
)

val GoldenEmpireDarkThemeColors = darkColorScheme(
    primary = Color(0xFFF4C04C),
    onPrimary = Color(0xFF3E2E00),
    primaryContainer = Color(0xFF5A4300),
    onPrimaryContainer = Color(0xFFFFE08A),
    secondary = Color(0xFFDFC56D),
    onSecondary = Color(0xFF393000),
    secondaryContainer = Color(0xFF524600),
    onSecondaryContainer = Color(0xFFFCE186),
    tertiary = Color(0xFFFFB59D),
    onTertiary = Color(0xFF5F1600),
    tertiaryContainer = Color(0xFF862200),
    onTertiaryContainer = Color(0xFFFFDBCF),
    error = Color(0xFFFFB4AB),
    errorContainer = Color(0xFF93000A),
    onError = Color(0xFF690005),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF15130B),
    onBackground = Color(0xFFE9E2D4),
    surface = Color(0xFF15130B),
    onSurface = Color(0xFFE9E2D4),
    surfaceVariant = Color(0xFF2B2818),
    onSurfaceVariant = Color(0xFFD4C8AC),
    outline = Color(0xFF9C9279),
    inverseOnSurface = Color(0xFF15130B),
    inverseSurface = Color(0xFFE9E2D4),
    inversePrimary = Color(0xFFC8941E),
)
